### PR TITLE
Add usage for feb 2023 to apr 2024

### PR DESCRIPTION
**Pull request by EliHaugu**
Went through our calendar, emails, and notable events since Feb 2023 (and a little before to correct a missing event) until now, please let me know if anything is missing or if there is a typo but I'm pretty sure I got all the dates correct at least :D

### CODE REVIEW

**Review by falbru — APPROVED** [review]
Awesome work 🤩 you da best

**Review by ivarnakken — APPROVED** [review]
Awesome! I never thought anyone would actually update this 🤩 🤩 
Only thing I spotted was that you didn't specify what _kind_ of Generalforsamling, but who cares 🤷🏼‍♂️ 

!! 🏅

**Comment by ivarnakken** [comment]
Wasn't vote used today?

**Comment by EliHaugu** [comment]
Wait was it? Do you know what it was used for @ivarnakken? I couldn't see anything for today on email or calendar but I might've missed something 😬 Thanks for letting me know 🫶

I can add which type of genfors, since it wasn't added for earlier entries I was unsure if I should add it but I can fix it on those as well! ^^

**Comment by ivarnakken** [comment]
> Wait was it? Do you know what it was used for @ivarnakken? I couldn't see anything for today on email or calendar but I might've missed something 😬 Thanks for letting me know 🫶

Didn't you vote for opptaksansvarlig? I didn't pay that much attention at that time, so not sure if you dropped that

**Comment by EliHaugu** [comment]
Ahh I see, I couldn't attend the beginning of today's meeting and came a little after the vote so forgot about that one. Thanks for letting me know, I'll add it! 🌸

**Comment by EliHaugu** [comment]
Added the new date and type of genfors, as well as a little error I noticed with Ordinær Generalforsamling 2022 (unless it was moved and not updated on Abakus or some other thing, if so please let me know)
image
image

**Pull request merged**
